{% set name = "data-diff" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f2adb8946126a7678533df4f01a95d7631cc9a0d4b92583a43d2d86eddc2601

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - data-diff = data_diff.__main__:main
    - sqeleton = data_diff.sqeleton.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7.2,<4.0.0
  run:
    - click >=8.1.0,<9.0.0
    - dbt-artifacts-parser >=0.4.0,<0.5.0
    - dbt-core >=1.0.0,<2.0.0
    - dsnparse <0.2.0
    - keyring
    - python >=3.7.2,<4.0.0
    - pyyaml
    - rich
    - runtype >=0.2.6,<0.3.0
    - tabulate >=0.9.0,<0.10.0
    - toml >=0.10.2,<0.11.0
    - typing_extensions
    - urllib3 <2

    # These are required though not listed in upstream requirements
    - packaging
    - pydantic
    - requests

test:
  imports:
    - data_diff
  commands:
    # Skip pip check due to prance version checking being broken
    # - pip check
    - data-diff --help
    - sqeleton --help
  requires:
    - pip

about:
  home: https://github.com/datafold/data-diff
  doc_url: https://data-diff.readthedocs.io/en/latest/
  summary: Command-line tool and Python library to efficiently diff rows across two different databases.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
