{% set name = "data-diff" %}
{% set version = "0.9.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a68a850923f3e4b9225a46e60c4c65226b91a6dc1e05b1f6a55890bd140ce110

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  # Skip on s390x because dbt-core is not available on that platform.
  skip: true  # [py<38 or s390x]
  entry_points:
    - data-diff = data_diff.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
  run:
    - python
    - pydantic ==1.10.12
    - dsnparse <0.2.0
    - click >=8.1.0,<9.0.0
    - rich
    - toml >=0.10.2,<0.11.0
    - dbt-core >=1.0.0,<2.0.0
    - keyring
    - tabulate >=0.9.0,<0.10.0
    - urllib3 <2
    - typing-extensions >=4.0.1
    - attrs >=23.1.0,<24.0.0
    - mashumaro >=2.9,<3.11.0

    # These are required though not listed in upstream requirements
    - packaging
    - requests

    # From mashumaro[msgpack]
    - msgpack-python >=0.5.6

  run_constrained:
    - snowflake-connector-python >=3.0.2,<4.0.0

test:
  imports:
    - data_diff
  commands:
    # Skip pip check due to prance version checking being broken
    # - pip check
    - data-diff --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datafold/data-diff
  summary: Compare datasets fast, within or across SQL databases.
  description: Compare datasets fast, within or across SQL databases.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
  doc_url: https://data-diff.readthedocs.io
  dev_url: https://github.com/datafold/data-diff

extra:
  recipe-maintainers:
    - thewchan
